changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: Documentation
      labels:
        - documentation
        - doc
